### ISSUE TITLE
Support nested objects for array-like query params

### ISSUE THREAD

**Issue by jr-mhi** [directus/directus-sdk-javascript#19]
getItems with sort parameter seems to be broken. The PHP expects an associative array: `array("sort" => "DESC")`, but sending an Array from JS (`client.getItems('articles', {sort: ['date']})`) fails since it's interpreted as `('0'=>'sort')`. Trying JSON `{date:'DESC'}` also fails since it gets interpreted as a String.

**Comment by rijkvanzanten** [comment]
The syntax of the API param is `?order[field]=ASC`. Since the params get translated to the query string directly (key: value => key=value), this should work by running:  
```javascript
client.getItems('articles', {
  'order[date]': 'DESC'
});
```

So technically, the SDK isn't broken per se, but uses a somewhat off-putting syntax in JS.

I'll leave this open as a feature request to be able to support something like:

```javascript
client.getItems('articles', {
  order: {
    date: 'ASC'
  }
});
```

which would also work for other parameters which use a comparable syntax, like `in[field]` and `filters[]`. 

What do you think?

**Comment by jr-mhi** [comment]
Aah! I see, if possible it would be nice to be able to use a little more standard syntax, but non-standard is still much better than broken. Thank you very much!

**Comment by mkleywegt** [comment]
This is an easy fix using a querystring parsing and stringifying library like the [qs package](https://www.npmjs.com/package/qs), as per the [Axios docs](https://github.com/axios/axios#request-config):
```js
axios.get(this.url + endpoint, {
  params,
  headers,
  paramsSerializer: params => qs.stringify(params, { arrayFormat: 'brackets' })
})
```
Can confirm that this works using version 2.2.0
