### ISSUE TITLE
React Native gives: Metro Bundler has encountered an internal error...

### ISSUE THREAD

**Issue by u12206050** [directus/directus-sdk-javascript#29]
Trying to build a react-native mobile app using directus-sdk. But when just importing it into my project I get a red screen in the emulator with the message: "Metro Bundler has encountered an internal error, please check your terminal error output for more details"

Can anyone confirm this sdk works with React-Native, and if NOT, what should I use instead?

Thanks.

**Comment by rijkvanzanten** [comment]
Hey @u12206050!

The SDK should work within React Native as well, since that’s also an JS environment. Could you maybe paste the terminal error output? I’d love to figure out what is causing the problem and get it resolved :-)

As an alternative, you can use any HTTP client that works with React Native and make the calls to the API endpoints directly.

Thanks in advance! 😊

**Comment by u12206050** [comment]
I get it working by importing from remote eg: `import RemoteInstance from 'directus-sdk-javascript/remote';`

**Comment by u12206050** [comment]
There isn't any errors in the console, don't know if I am debugging it wrong then.
